### ISSUE TITLE
Documentation README lists invalid usage examples

### ISSUE THREAD

**Issue by ryanjbonnell** [derimagia/terminus-pancakes#12]
The README in the current version of Pancakes suggests being able to use the following commands (citing Sequel Pro as an example):

`$ terminus site sequel --site=my-company --env=dev`

However, when trying to run this Terminus command, it errors with the following message:

```
[2016-11-17 23:23:17] [error] 'site sequel' is not a registered command.
See 'terminus help'. cmd: 'site sequel'
```

The correct command usage is actually:

`$ terminus site pancakes --app=sequelpro --site=my-company --env=dev`

This was verified using the Terminus built-in help command:

`$ terminus help site`

Please update the documentation with current usage examples. I'm happy to submit a pull request with the changes if you're open to contributions.

Tested using Terminus 0.13.5.

**Comment by derimagia** [comment]
Thanks for letting me know this! I updated the main doc. Can you verify it works for you? 

I'm always open for contributions.

**Comment by ryanjbonnell** [comment]
Yes, I can confirm the updated examples in the documentation work as expected.
