### ISSUE TITLE
Proposed title change

### ISSUE THREAD

**Issue by uberhacker** [derimagia/terminus-pancakes#9]
The repo title still suggests this plugin only works for Sequel Pro: "Terminus Plugin to open Pantheon Databases in SequelPro".  Maybe it should say: "Terminus plugin to open Pantheon site databases in a SQL GUI client"?

**Comment by derimagia** [comment]
Thanks for the reminder! Changed it to "Terminus Plugin to open Pantheon Site Databases in your Favorite SQL GUI Client"
